// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3KXgwM4FDetdqyl8g7jj9wHZCLZvfno',
    appId: '1:355482824296:web:03d2675620814f1493d5dd',
    messagingSenderId: '355482824296',
    projectId: 'pan-property-advisor-v1',
    authDomain: 'pan-property-advisor-v1.firebaseapp.com',
    storageBucket: 'pan-property-advisor-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXlE_TlMvrV4O8ZzzFfzX_8BeaizAj3s',
    appId: '1:355482824296:android:5a60727535def89d93d5dd',
    messagingSenderId: '355482824296',
    projectId: 'pan-property-advisor-v1',
    storageBucket: 'pan-property-advisor-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjgQZxZMADTr2c1YJpHhkMRZiN6MpucWs',
    appId: '1:355482824296:ios:86379fd729df997c93d5dd',
    messagingSenderId: '355482824296',
    projectId: 'pan-property-advisor-v1',
    storageBucket: 'pan-property-advisor-v1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1pan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjgQZxZMADTr2c1YJpHhkMRZiN6MpucWs',
    appId: '1:355482824296:ios:86379fd729df997c93d5dd',
    messagingSenderId: '355482824296',
    projectId: 'pan-property-advisor-v1',
    storageBucket: 'pan-property-advisor-v1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1pan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo3KXgwM4FDetdqyl8g7jj9wHZCLZvfno',
    appId: '1:355482824296:web:769ecee95cb0eb7093d5dd',
    messagingSenderId: '355482824296',
    projectId: 'pan-property-advisor-v1',
    authDomain: 'pan-property-advisor-v1.firebaseapp.com',
    storageBucket: 'pan-property-advisor-v1.firebasestorage.app',
  );
}
